language: cpp
compiler:
  - gcc
  - clang
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script:
  - mkdir build 
  - cd build 
  - cmake .. 
  - make
  - "export DISPLAY=:99.0"
  - cd tests
  - ./runTests

