# lots of thanks to https://github.com/hicknhack-software/QSqlMigrator/blob/master/appveyor.yml !

environment:
  matrix:
  - BUILD: MSVS2010
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETCOMPILER: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
    QTDOWNLOAD1: http://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe
    QTARCHIVE1: qt-opensource-windows-x86-vs2010-4.8.7.exe
    CMAKECALL: 'cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .'
    MAKECALL: nmake
    
  - BUILD: MINGW32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    SETCOMPILER: 'set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%'
    QTDOWNLOAD1: http://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe
    QTARCHIVE1: qt-opensource-windows-x86-mingw482-4.8.7.exe
    CMAKECALL: 'cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .'
    MAKECALL: mingw32-make

install:
  #- choco install curl
  - mkdir extern
  - cd extern
  - mkdir Qt
  - cd Qt
  - curl -kLO %QTDOWNLOAD1%
  - 7z x "-ir!?_14_\*" "-xr!*doc\*" "-xr!*examples\*" "-xr!*demos\*" %QTARCHIVE1%
  - move $_14_ 4.8.7
  - set QTDIR=%CD%\4.8.7
  - echo [Paths] >%QTDIR%\bin\qt.conf
  - echo Prefix=.. >>%QTDIR%\bin\qt.conf
  - set QT_PLUGIN_PATH=%QTDIR%\plugins
  - cd ..
  - cd ..
  - '%SETCOMPILER%'
  - set PATH=%QTDIR%\bin;%PATH%
  - move "C:\Program Files\Git\usr\bin\sh.exe" "C:\Program Files\Git\usr\bin\shxx.exe"


build_script:
  - '%CMAKECALL%'
  - '%MAKECALL%'

test_script:
  - cd tests
  - runTests.exe
