# lots of thanks to https://github.com/pcolby/libqtaws/blob/master/.appveyor.yml !

environment:
  VSVER: 12.0 # Visual Studio 2013
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32
    - QTDIR: C:\Qt\5.5\msvc2013
    - QTDIR: C:\Qt\5.5\msvc2013_64


configuration:
  - Debug
  - Release

install:
  # Setup the build toolchains.
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - echo %ARCH%
  - echo %QTDIR%
  - echo %QTDIR:msvc=%
  - cd "C:/Program Files (x86)/Git/bin"
  - ren sh.exe shxx.exe
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if %QTDIR:msvc=%==%QTDIR% set cmakecall=cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul
  - if not %QTDIR:msvc=%==%QTDIR% set cmakecall=cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%


before_build:
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%cmakecall%'

build_script:
  - '%make%'


# disable tests for now
#test_script:
  #- cd tests
  #- runTests.exe
